import { useState } from 'react';
import { ConversationPanel } from '@/components/ConversationPanel';
import { ActionBar } from '@/components/ActionBar';
import { AnalysisPanel } from '@/components/AnalysisPanel';
import { useToast } from '@/hooks/use-toast';
import { Bot } from 'lucide-react';
import { sampleAnalysis } from '@/data/analysisData';

function buildExportJson(customMode: boolean, customText: string) {
  const r = sampleAnalysis;
  return {
    meta: {
      generatedAt: new Date().toISOString(),
      client: r.client,
      period: r.period,
      conversationSource: customMode && customText.trim() ? 'custom' : 'sample',
      note:
        'In production, this would be generated by an LLM analyzing the conversation. Confidence scores reflect evidence quality.',
    },
    weeklySummary: {
      text: r.weeklySummary.text,
      confidence: r.weeklySummary.confidence,
    },
    nutrition: {
      value: r.nutrition.value,
      summary: r.nutrition.summary,
      confidence: r.nutrition.confidence,
      classification: r.nutrition.classification,
      evidence: r.nutrition.evidence,
    },
    exercise: {
      value: r.exercise.value,
      summary: r.exercise.summary,
      confidence: r.exercise.confidence,
      classification: r.exercise.classification,
      evidence: r.exercise.evidence,
    },
    sleep: {
      value: r.sleep.value,
      summary: r.sleep.summary,
      confidence: r.sleep.confidence,
      classification: r.sleep.classification,
      evidence: r.sleep.evidence,
    },
    waterIntake: {
      value: r.waterIntake.value,
      summary: r.waterIntake.summary,
      confidence: r.waterIntake.confidence,
      classification: r.waterIntake.classification,
      evidence: r.waterIntake.evidence,
    },
    symptoms: {
      value: r.symptoms.value,
      summary: r.symptoms.summary,
      confidence: r.symptoms.confidence,
      classification: r.symptoms.classification,
      evidence: r.symptoms.evidence,
    },
    engagement: {
      value: r.engagement.value,
      summary: r.engagement.summary,
      confidence: r.engagement.confidence,
      classification: r.engagement.classification,
    },
    keyBarriers: r.keyBarriers,
    pendingActions: r.pendingActions,
    riskFlags: r.riskFlags,
    coachRecommendation: r.coachRecommendation,
    supportingEvidence: r.allEvidence,
  };
}

export default function Dashboard() {
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [isAnalyzed, setIsAnalyzed] = useState(false);
  const [customText, setCustomText] = useState('');
  const [isCustomMode, setIsCustomMode] = useState(false);
  const { toast } = useToast();

  const handleAnalyze = () => {
    setIsAnalyzing(true);
    setTimeout(() => {
      setIsAnalyzing(false);
      setIsAnalyzed(true);
      toast({ title: 'Analysis Complete', description: 'Client intelligence report generated.' });
    }, 1500);
  };

  const handleApprove = () => {
    toast({ title: 'Approved', description: 'Insights saved to client record.' });
  };

  const handleReject = () => {
    toast({ title: 'Rejected', description: 'Flagged for manual review.', variant: 'destructive' });
    setIsAnalyzed(false);
  };

  const handleEdit = () => {
    toast({ title: 'Edit Mode', description: 'You can now edit the generated insights.' });
  };

  const handleExportJson = () => {
    const data = buildExportJson(isCustomMode, customText);
    const blob = new Blob([JSON.stringify(data, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `fume-intelligence-report-${Date.now()}.json`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: 'JSON Exported', description: 'Report downloaded successfully.' });
  };

  return (
    <div className="h-[100dvh] w-full bg-background flex flex-col lg:flex-row overflow-hidden">
      {/* Left Panel */}
      <div className="w-full lg:w-[420px] shrink-0 h-[45vh] lg:h-full z-20 overflow-hidden">
        <ConversationPanel
          customText={customText}
          onCustomTextChange={setCustomText}
          isCustomMode={isCustomMode}
          onToggleMode={setIsCustomMode}
        />
      </div>

      {/* Center Action Bar */}
      <div className="h-auto lg:h-full shrink-0 z-30">
        <ActionBar
          onAnalyze={handleAnalyze}
          isAnalyzing={isAnalyzing}
          isAnalyzed={isAnalyzed}
          onApprove={handleApprove}
          onReject={handleReject}
          onEdit={handleEdit}
          onExportJson={handleExportJson}
        />
      </div>

      {/* Right Panel */}
      <div className="flex-1 overflow-hidden bg-slate-50">
        {!isAnalyzed ? (
          <div className="h-full flex flex-col items-center justify-center p-8 text-center">
            <div className="w-16 h-16 bg-primary/5 rounded-full flex items-center justify-center mb-4">
              <Bot className="w-8 h-8 text-primary/40" />
            </div>
            <h3 className="text-lg font-semibold text-foreground mb-2">Ready for Analysis</h3>
            <p className="text-sm text-muted-foreground max-w-xs">
              {isCustomMode && customText.trim()
                ? 'Click Analyze to process your custom conversation.'
                : 'Click the Analyze button to generate a comprehensive 8-day client intelligence report.'}
            </p>
            {isCustomMode && !customText.trim() && (
              <p className="text-xs text-amber-600 mt-3 max-w-xs">
                Paste your conversation in the left panel before analyzing.
              </p>
            )}
          </div>
        ) : (
          <AnalysisPanel />
        )}
      </div>
    </div>
  );
}
